### ISSUE TITLE
Regsiter ui - problems with German translations

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/auth#103]
# Label "Kennwortbestätigung" shouldn't be cut.

![grafik](https://user-images.githubusercontent.com/26661092/29615724-4b6871a0-880f-11e7-8d2b-7d95f722d565.png)

# Error message on wrong verification token

![grafik](https://user-images.githubusercontent.com/26661092/29616018-385ba8ec-8810-11e7-95b5-29cdc17cef77.png)

**Comment by sureshvarman-cronj** [comment]
UI changed on PR https://github.com/OpusCapita/auth/pull/112
