### ISSUE TITLE
Logout redirect override

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/auth#114]
We need this controllable by caller.
# Use case

User in BNP wants to hit login screen after loggin out, then if loggin in again wants to be redirected to businessnetwork.opuscapita.com

User in OCI wants to hit login screen after logout, then when loggin in again needs redirect to businessnetwork.opuscapita.com/invoice

# Implementation

Proposing to use url parameter to logout and login page
/auth/logout?backTo=/invoice
then
after interaction we should redirect to the value stored (e.g. use cookie if to hard to wire through interaction)

**Comment by sureshvarman-cronj** [comment]
Now auth/logout takes query string as `backTo`, each service can define its own `backTo` in `auth/logout` link.

**Comment by sureshvarman-cronj** [comment]
Need to add the same features in react menu component to decide the service based on the current service. E.G. **/auth/logout?backTo=/ANY_SERVICE_OR_PATH**

**Comment by dzhitomirsky-sc** [comment]
Thanks! I works.
