### ISSUE TITLE
Make email lowercase

### ISSUE THREAD

**Issue by kwierchris** [OpusCapita/auth#117]
The email address (username) should be stored and compared (on login, reset password) in small letters or case insensitive.

**Comment by sureshvarman-cronj** [comment]
It seems auth is using sequelizejs findBy, and Database is by default case insensitive, and also we are querying the user service on login, and user service is using findById, which is off course a binary comparison, so it seems to be failed. have to change that in user service.

```
ALTER TABLE `User` MODIFY
`userId` VARCHAR(50) 
CHARACTER SET latin1
COLLATE latin1_bin;
```

**Comment by kwierchris** [comment]
But we will **not** switch to latin1 charset.
