### ISSUE TITLE
 Unhandled rejection SequelizeDatabaseError: ER_NO_SUCH_TABLE: Table 'bnp.UserOnboardData' doesn't exist

### ISSUE THREAD

**Issue by patrykkopycinski** [OpusCapita/auth#17]

**Comment by gr4per** [comment]
Data migrations were screwed:
* wrong names, so partial execution
* wrong implementation of up/down (logical errors, non-existing columns)
* wrong sequence of execution (missing Promise return caused race condition)
* incorrect sample data 

This was really messed up and took time to fix.
Apparently it was never even tested locally.
