### ISSUE TITLE
Refactor user onboardData to user service

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/auth#18]
Remove sequelize model
Remove api endpoint
Create card in user service to add the code over there

In places where accessign onboardInfo, refactor to call user service via REST

**Comment by gr4per** [comment]
Basically just allow to pass onboardInfo as additional sub structure to user service when creating user?

**Comment by sureshvarman-cronj** [comment]
Created in user service, now uses user registration and onboarding from user service, have to cleanup the code, so kept opening
