### ISSUE TITLE
After email registration, login should prepopulate user email into login form

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/auth#22]
This info is available on user of course, so just use query param to inject it

**Comment by gr4per** [comment]
![image](https://cloud.githubusercontent.com/assets/22681804/24950053/f9b71a6c-1f6f-11e7-9d8f-a5e3ec1ef478.png)
This is the form that needs email populated

**Comment by sureshvarman-cronj** [comment]
populated email after login, need to find out a way for initial service to be hit, since the oidc is interaction, right now it is /bnp
