### ISSUE TITLE
Map user fields as claims

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/auth#23]

**Comment by sureshvarman-cronj** [comment]
federationId
        supplierId 
        customerId
        status
        mayChangeSupplier
        mayChangeCustomer

will add the above fields to userInfo claims, we already supplierid, customerId and status, do we need audit information also to be the claim, will any service requires this audit informations

**Comment by gr4per** [comment]
No don't need audit. But the additional fields from profile would help
