### ISSUE TITLE
Clicking login after email confirmation should prepopulate user email on login

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/auth#32]
you can use query params for that, but we need the name there in order to prevent user from retyping it

**Comment by nczeranka** [comment]
Auth already checks for a Cookie named "registeredEmail" and prefills the email in the login ui.
Easiest approach would be to store the registered email in the Cookie on on successfull approval of the user with the registration code. Maybe with a timeout on the Cookie of e.g. 10 minutes.

**Comment by nczeranka** [comment]
Adjustment tested succesfully on the dev system.
