### ISSUE TITLE
Use bluebird for Promises

### ISSUE THREAD

**Issue by nczeranka** [OpusCapita/auth#41]
To harmonize our code, we have to use bluebird Promises instead of the promise package.

Problem will be that 'bluebird' does not allow other objects than Error objects. So a construct like
`return Promise.reject({statusCode: 409, message: 'Mail already exists'});`
will result in an error log entry.

**Comment by kwierchris** [comment]
Using bluebird would result in a line like this for the above code:
Promise.reject(new Error('Mail already exists'));
